main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: Levi Muniz
description: A simple UHC plugin

commands:
  uhc:
    description: Base command for UHC

permissions:
  uhc.admin:
    description: Gives players access to administrative commands
    default: op